const express = require('express');
const GiftOrder = require('../models/GiftOrder');
const GiftPackage = require('../models/GiftPackage');
const { auth, staffAuth } = require('../middleware/auth');
const cacheMiddleware = require('../middleware/cache');
const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

const router = express.Router();

function giftOrderEmailTemplate({
  senderName, recipientName, recipientEmail, deliveryDate, giftPackage, message, price
}) {
  return `
    <h2>Tassel Group – Gift Package Order Confirmation</h2>
    <p><strong>Sender:</strong> ${senderName}</p>
    <p><strong>Recipient Name:</strong> ${recipientName}</p>
    <p><strong>Recipient Email:</strong> ${recipientEmail}</p>
    <p><strong>Scheduled Delivery:</strong> ${deliveryDate ? new Date(deliveryDate).toLocaleDateString() : ''}</p>
    <hr>
    <h3>Gift Package: ${giftPackage.name}</h3>
    <p>${giftPackage.description}</p>
    <h4>INCLUDES:</h4>
    <ul>
      ${Array.isArray(giftPackage.includes)
      ? giftPackage.includes.map(i => `<li>${i}</li>`).join('')
      : '<li>Description only</li>'
    }
    </ul>
    <p><strong>Personal Message:</strong> ${message || '(none)'}</p>
    <h3>Total Price: R ${price.toFixed(2)}</h3>
    <hr>
    <small>This confirmation was automatically generated by Tassel Group.</small>
  `;
}

// Create gift order
router.post('/', cacheMiddleware(300), auth, async (req, res) => {
  try {
    const { giftPackage, recipientName, recipientEmail, message, deliveryDate, assignedStaff } = req.body;

    console.log('🎁 Gift order creation request:', {
      user: req.user._id,
      body: req.body
    });

    // Validate required fields
    if (!giftPackage) {
      return res.status(400).json({ message: 'Gift package ID is required' });
    }
    if (!recipientName) {
      return res.status(400).json({ message: 'Recipient name is required' });
    }
    if (!recipientEmail) {
      return res.status(400).json({ message: 'Recipient email is required' });
    }
    if (!deliveryDate) {
      return res.status(400).json({ message: 'Delivery date is required' });
    }

    // Find the gift package to get price
    const giftPackageDoc = await GiftPackage.findById(giftPackage);
    if (!giftPackageDoc) {
      return res.status(404).json({ message: 'Gift package not found' });
    }

    // Create gift order
    const giftOrder = new GiftOrder({
      user: req.user._id,
      giftPackage,
      recipientName,
      recipientEmail,
      message: message || '',
      deliveryDate: new Date(deliveryDate),
      price: giftPackageDoc.basePrice || giftPackageDoc.price || 0,
      assignedStaff: assignedStaff || null,
      status: 'pending'
    });

    await giftOrder.save();
    await giftOrder.populate('giftPackage', 'name description basePrice includes');
    await giftOrder.populate('assignedStaff', 'name email');

    // Look up sender details
    const User = require('../models/User');
    const senderDoc = await User.findById(req.user._id);

    // Prepare and send confirmation emails
    const html = giftOrderEmailTemplate({
      senderName: senderDoc?.name || 'Tassel User',
      recipientName,
      recipientEmail,
      deliveryDate,
      giftPackage: giftOrder.giftPackage,
      message,
      price: giftOrder.price
    });

    // Send email to recipient
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: recipientEmail,
      subject: "Your Tassel Group Gift Order",
      html
    });

    // Send email to Tassel admin
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: "info@tasselgroup.co.za",
      subject: `New Gift Package Order – ${recipientName}`,
      html
    });

    console.log('✅ Gift order created and emails sent:', giftOrder._id);

    res.status(201).json(giftOrder);

  } catch (error) {
    console.error('❌ Gift order creation error:', error);
    res.status(500).json({
      message: 'Server error creating gift order',
      error: error.message
    });
  }
});

// PATCH /api/gift-orders/:id - Update gift order
router.patch('/:id', auth, async (req, res) => {
  try {
    const { status, assignedStaff, deliveryDate } = req.body;
    const updateData = {};

    if (status) updateData.status = status;
    if (assignedStaff) updateData.assignedStaff = assignedStaff;
    if (deliveryDate) updateData.deliveryDate = deliveryDate;

    const giftOrder = await GiftOrder.findByIdAndUpdate(
      req.params.id,
      updateData,
      { new: true, runValidators: true }
    ).populate('user', 'name email')
      .populate('giftPackage', 'name basePrice')
      .populate('assignedStaff', 'name email');

    if (!giftOrder) {
      return res.status(404).json({ success: false, message: 'Gift order not found' });
    }

    res.json({ success: true, giftOrder });
  } catch (error) {
    console.error('Error updating gift order:', error);
    res.status(500).json({ success: false, message: 'Server error' });
  }
});

router.patch('/:id/status', staffAuth, async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    console.log(`🔄 Updating gift order ${id} status to: ${status}`);

    const giftOrder = await GiftOrder.findByIdAndUpdate(
      id,
      { status },
      { new: true }
    ).populate('user giftPackage assignedStaff');

    if (!giftOrder) {
      return res.status(404).json({
        success: false,
        message: 'Gift order not found'
      });
    }

    console.log(`✅ Gift order status updated successfully: ${giftOrder.status}`);
    res.json({
      success: true,
      giftOrder
    });

  } catch (error) {
    console.error('❌ Gift order status update error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating gift order status',
      error: error.message
    });
  }
});

// Get user's gift orders
router.get('/my-gift-orders', auth, async (req, res) => {
  try {
    const giftOrders = await GiftOrder.find({ user: req.user._id })
      .populate('giftPackage', 'name description basePrice includes')
      .populate('assignedStaff', 'name email')
      .sort({ createdAt: -1 });

    res.json(giftOrders);
  } catch (error) {
    console.error('Error fetching user gift orders:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});


// ============================================================================
// GET STAFF ASSIGNED GIFT ORDERS - FOR STAFF DASHBOARD
// ============================================================================

// Get staff assigned gift orders (for staff dashboard)
router.get('/staff/assigned', auth, async (req, res) => {
  try {
    const staffId = req.user._id;

    const giftOrders = await GiftOrder.find({ assignedStaff: staffId })
      .populate('giftPackage', 'name basePrice')
      .populate('user', 'name email')
      .sort({ deliveryDate: -1 })
      .lean();

    console.log(`✅ Staff gift orders for ${req.user.name}:`, giftOrders.length);

    res.json({
      success: true,
      data: giftOrders,
      bookings: giftOrders
    });
  } catch (error) {
    console.error('❌ Error fetching staff gift orders:', error);
    res.status(500).json({
      success: false,
      message: 'Error loading gift orders',
      error: error.message
    });
  }
});

// Get all gift orders (staff and admin)
router.get('/', staffAuth, async (req, res) => {
  try {
    let giftOrders;
    if (req.user.role === 'admin') {
      giftOrders = await GiftOrder.find()
        .populate('user', 'name email')
        .populate('giftPackage', 'name description basePrice includes')
        .populate('assignedStaff', 'name email')
        .sort({ createdAt: -1 });
    } else {
      // Staff can see orders assigned to them
      giftOrders = await GiftOrder.find({ assignedStaff: req.user._id })
        .populate('user', 'name email')
        .populate('giftPackage', 'name description basePrice includes')
        .populate('assignedStaff', 'name email')
        .sort({ createdAt: -1 });
    }

    res.json(giftOrders);
  } catch (error) {
    console.error('Error fetching gift orders:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

// Update gift order status
router.put('/:id/status', staffAuth, async (req, res) => {
  try {
    const { status } = req.body;
    const giftOrder = await GiftOrder.findByIdAndUpdate(
      req.params.id,
      { status },
      { new: true }
    )
      .populate('user', 'name email')
      .populate('giftPackage', 'name description basePrice includes')
      .populate('assignedStaff', 'name email');

    if (!giftOrder) {
      return res.status(404).json({ message: 'Gift order not found' });
    }

    res.json(giftOrder);
  } catch (error) {
    console.error('Error updating gift order status:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

router.get('/user/:userId', staffAuth, async (req, res) => {
  try {
    const giftOrders = await GiftOrder.find({ user: req.params.userId })
      .populate('giftPackage', 'name description basePrice includes')
      .populate('assignedStaff', 'name email')
      .sort({ createdAt: -1 });
    res.json(giftOrders);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});


module.exports = router;